# Generated by Django 6.0.7 on 2026-07-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('customer', 'Customer'), ('business', 'Business')], default='business', max_length=20),
            preserve_default=False,
        ),
    ]
